import type { Bootstrap, Settings } from "../types";

export function makeBootstrap(settingsOverride: Partial<Settings> = {}): Bootstrap {
  return {
    capabilities: {},
    roots: [],
    settings: {
      directory: "/tmp/pdfs",
      single_file: "",
      language: "de",
      case: "kebabCase",
      date_format: "dmy",
      preset: "",
      project: "",
      version: "",
      template: "",
      backup_dir: "",
      rename_log: "",
      export_metadata: "",
      summary_json: "",
      rules_file: "",
      post_rename_hook: "",
      llm_url: "",
      llm_model: "",
      llm_timeout: "",
      max_tokens: "",
      max_content_chars: "",
      max_content_tokens: "",
      workers: "1",
      max_filename_chars: "",
      dry_run: true,
      use_llm: false,
      use_ocr: false,
      recursive: false,
      skip_already_named: false,
      use_pdf_metadata_date: true,
      use_structured_fields: true,
      write_pdf_metadata: false,
      use_vision_fallback: false,
      simple_naming_mode: false,
      vision_first: false,
      acknowledged_external_endpoint: "",
      ...settingsOverride,
    },
  };
}
